### ISSUE TITLE
Описание на различните command-line опции за проверки в readme-то

### ISSUE THREAD

**Issue by mitio** [skanev/skeptic#15]
Смятам, че има нужда да добавим такава информация. В момента няма централизирана и синтезирана документация какви проверки се поддържат от skeptic и как могат да се параметризират и управляват.

Представям си нещо от рода на:

---

## Supported Checks

This section describes the different checks skeptic supports and how you can activate them via the command-line using the `bin/skeptic` tool:

- `lines-per-method=NUMBER` -- the maximum number of lines allowed in a method definition. Blank lines, `end` keyword, etc. are not counted. Semicolons are counted as newlines, though.
- `line-length=NUMBER` -- ...
- `max-nesting-depth=NUMBER` -- ...
- `methods-per-class=NUMBER` -- ...
- `no-semicolons` -- ...
- `no-trailing-whitespace` -- ...
- `check-syntax` -- ...
- `no-global-variables` -- ...
- `english-words-for-names='list of word exceptions'` -- ...
- `naming-conventions` -- ...
- `spaces-around-operators` -- ...

A complete example:

	skeptic \
	--lines-per-method=4 \
	--line-length=80 \
	--max-nesting-depth=1 \
	--methods-per-class=9 \
	--no-semicolons \
	--no-trailing-whitespace \
	--check-syntax \
	--no-global-variables \
	--english-words-for-names='list of word exceptions' \
	--naming-conventions \
	--spaces-around-operators \
	path_to_ruby_file.rb

**Comment by alehander42** [comment]
В някакъв момент е направено :+1:
